<?php
/**
 * This HTML controller is what generates HTML pages (as opposed to JSON responses
 * generated by the other controllers).  The reason is testability: most of the 
 * manager app can be tested by $scriptProperties in, JSON out.  The HTML pages
 * generated by this controller end up being static HTML pages (well... ideally, 
 * anyway). 
 *
 * See http://stackoverflow.com/questions/10941249/separate-rest-json-api-server-and-client
 *
 * See the IndexManagerController class (index.class.php) for routing info.
 *
 * @package assman
 */
namespace Assman;
class PageController extends BaseController {

    public $loadHeader = false;
    public $loadFooter = false;
    // GFD... this can't be set at runtime. See improvised addStandardLayout() function
    public $loadBaseJavascript = false; 
    // Stuff needed for interfacing with Assman API (mapi)
    public $client_config = array();
    
    function __construct(\modX &$modx,$config = array()) {
        parent::__construct($modx,$config);
        static::$x =& $modx;

        $this->config['controller_url'] = self::url();
        $this->config['core_path'] = $this->modx->getOption('assman.core_path', null, MODX_CORE_PATH.'components/assman/');
        $this->config['assets_url'] = $this->modx->getOption('assman.assets_url', null, MODX_ASSETS_URL.'components/assman/');
                
        $this->modx->regClientCSS($this->config['assets_url'] . 'css/mgr.css');
        $this->modx->regClientCSS($this->config['assets_url'] . 'css/dropzone.css');
        $this->modx->regClientCSS('//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
        $this->modx->regClientCSS($this->config['assets_url'].'css/colorbox.css');        
//        $this->modx->regClientCSS($this->config['assets_url'].'css/jquery-ui.css'); // smoothness        
//        $this->modx->regClientStartupScript($this->config['assets_url'].'js/jquery.min.js');
        $this->modx->regClientStartupScript($this->config['assets_url'].'js/jquery.js');
        $this->modx->regClientStartupScript($this->config['assets_url'].'js/jquery-ui.js');
        $this->modx->regClientStartupScript($this->config['assets_url'].'js/handlebars.js');
        $this->modx->regClientStartupScript($this->config['assets_url'].'js/dropzone.js');
        $this->modx->regClientStartupScript($this->config['assets_url'].'js/bootstrap.js');
        $this->modx->regClientStartupScript($this->config['assets_url'].'js/form2js.js');
        $this->modx->regClientStartupScript($this->config['assets_url'].'js/jquery.colorbox.js');                      
        $this->modx->regClientStartupScript($this->config['assets_url'].'js/multisortable.js');  
        $this->modx->regClientStartupScript($this->config['assets_url'].'js/jquery.quicksand.js');      
    }


    //------------------------------------------------------------------------------
    //! Assets
    //------------------------------------------------------------------------------
    /**
     * Asset management main page
     *
     * @param array $scriptProperties
     */
    public function getAssets(array $scriptProperties = array()) {
        $this->modx->log(\modX::LOG_LEVEL_INFO, print_r($scriptProperties,true),'','Asset Manager PageController:'.__FUNCTION__);
        $A = $this->modx->getObject('Asset');
        $results = $Obj->all($scriptProperties);
        $this->setPlaceholder('results', $results);
        $this->setPlaceholders($scriptProperties);
        return $this->fetchTemplate('main/assets.php');
    }
    
    //------------------------------------------------------------------------------
    //! Index
    //------------------------------------------------------------------------------
    /**
     * @param array $scriptProperties
     */
    public function getIndex(array $scriptProperties = array()) {
        $this->modx->log(\modX::LOG_LEVEL_INFO, print_r($scriptProperties,true),'','Asset Manager PageController:'.__FUNCTION__);
        return $this->fetchTemplate('main/index.php');
    }

    //------------------------------------------------------------------------------
    //! Groups
    //------------------------------------------------------------------------------
    public function getGroups(array $scriptProperties = array()) {
        $this->modx->log(\modX::LOG_LEVEL_INFO, print_r($scriptProperties,true),'','Asset Manager PageController:'.__FUNCTION__);
        $A = $this->modx->newObject('Asset');
        $this->config['Groups'] = $A->getAssetGroups();
        $this->modx->regClientStartupHTMLBlock('<script type="text/javascript">
            var assman = '.json_encode($this->config).';
        </script>');
        
        return $this->fetchTemplate('group/manage.php');
    }
    
    public function postGroups(array $scriptProperties = array()) {
        $groups = $this->modx->getOption('groups', $scriptProperties);
        $groups = array_unique($groups);
        $groups = array_filter($groups);
        if (!$Setting = $this->modx->getObject('modSystemSetting', 'assman.groups')) {
            $Setting = $this->modx->newObject('modSystemSetting');
            $Setting->set('key', 'assman.groups');
            $Setting->set('xtype','textfield');
            $Setting->set('namespace','assman');
            $Setting->set('area','assman:default');       
        }
        $Setting->set('value', json_encode($groups));
        if (!$Setting->save()) {
        
        }
        // Clear cache
        $cacheRefreshOptions =  array( 'system_settings' => array() );
        $this->modx->cacheManager->refresh($cacheRefreshOptions);
        return $this->getGroups();
    }
    
    
    //------------------------------------------------------------------------------
    //! Settings
    //------------------------------------------------------------------------------
    /**
     * @param array $scriptProperties
     */
    public function getSettings(array $scriptProperties = array()) {
        $this->modx->log(\modX::LOG_LEVEL_INFO, print_r($scriptProperties,true),'','Asset Manager PageController:'.__FUNCTION__);
        return $this->fetchTemplate('main/settings.php');
     
    }
    
    //------------------------------------------------------------------------------
    //! Page
    //------------------------------------------------------------------------------
    /**
     * Generates a tab for Ext JS editing a resource
     * @param array $scriptProperties
     */
    public function getPageAssetsTab(array $scriptProperties = array()) {

        $this->modx->log(\modX::LOG_LEVEL_INFO, print_r($scriptProperties,true),'','Asset Manager PageController:'.__FUNCTION__);
        $page_id = (int) $this->modx->getOption('page_id', $scriptProperties);
        $this->config['page_id'] = $page_id;
        $this->setPlaceholder('page_id', $page_id);
        $this->scriptProperties['_nolayout'] = true;
        
        $PA = $this->modx->newObject('PageAsset');
        $A = $this->modx->newObject('Asset');
        $this->config['PageAssets'] = $PA->getAssets($page_id);
        $this->config['Groups'] = $A->getAssetGroups();

        $path = $this->modx->getOption('assman.core_path','', MODX_CORE_PATH.'components/assman/').'views/';
        $out = file_get_contents($path.'main/pageassets.tpl');

        // Wedge the output into the tab
        $this->modx->lexicon->load('assman:default');
        $title = $this->modx->lexicon('assets_tab');

        $this->modx->regClientStartupHTMLBlock('<script type="text/javascript">
            var assman = '.json_encode($this->config).';
            var inited = 0;
            MODx.on("ready",function() {
                console.log("[assman] on ready...");
                MODx.addTab("modx-resource-tabs",{
                    title: '.json_encode($title).',
                    id: "assets-resource-tab",
                    width: "95%",
                    html: '.json_encode($out).'
                });
                if (inited==0) {
                    page_init();
                }
            });                
        </script>');
        $this->modx->regClientStartupScript($this->config['assets_url'].'js/app.js');

    }            
}
/*EOF*/